version: '3.8'

services:
  devopscycledb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - devopscycle-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

  devopscycle-app:
    image: devopscycle-image
    environment:
      DB_HOST: devopscycledb
    networks:
      - devopscycle-network
    depends_on:
      devopscycledb:
        condition: service_healthy

networks:
  devopscycle-network:
    driver: bridge

