version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=boa
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devopscycle-network

networks:
  devopscycle-network:
    driver: bridge
